# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('pvlevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eletype', models.IntegerField(default=0)),
                ('picfile', models.FileField(upload_to=mysite.models.candidatepic_path)),
                ('sex', models.CharField(default=b'\xe7\x94\xb7', max_length=6)),
                ('birthyear', models.IntegerField(default=0)),
                ('backgroud', models.CharField(default=b'\xe5\xb0\x8f\xe5\xad\xa6', max_length=8)),
                ('nation', models.CharField(default=b'\xe6\xb1\x89\xe6\x97\x8f', max_length=16)),
                ('videourl', models.CharField(max_length=256)),
                ('politics', models.CharField(default=b'\xe7\xbe\xa4\xe4\xbc\x97', max_length=12)),
                ('othertext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=1)),
                ('val', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=1)),
                ('val', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docfile', models.FileField(upload_to=mysite.models.exl_path)),
            ],
        ),
        migrations.CreateModel(
            name='Judge_Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('type', models.IntegerField(db_index=True, default=0)),
                ('idsn', models.CharField(db_index=True, max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('frontpic', models.FileField(upload_to=mysite.models.frontpic_path)),
                ('backpic', models.FileField(upload_to=mysite.models.backpic_path)),
                ('finished', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_index=True, default=datetime.datetime.now, max_length=10)),
                ('action', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('docfile', models.FileField(blank=True, null=True, upload_to=mysite.models.pic_path)),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('pollcnt', models.IntegerField(default=0)),
                ('st', models.DateTimeField()),
                ('dt', models.DateTimeField()),
                ('commitcnt', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('type', models.IntegerField(db_index=True, default=0)),
                ('idsn', models.CharField(db_index=True, max_length=30)),
                ('addr', models.CharField(max_length=256)),
                ('birth', models.CharField(max_length=50)),
                ('suffix', models.CharField(db_index=True, default=b'', max_length=6)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('pwd', models.CharField(default=mysite.models.randpwd, max_length=40)),
                ('nation', models.CharField(max_length=30)),
                ('hashsn', models.CharField(db_index=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='User_Choice2_Rel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Choice2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Choice_Rel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User')),
            ],
        ),
        migrations.CreateModel(
            name='Valid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=20)),
                ('key', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Var',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('val', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='choice2',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices2', to='mysite.Question'),
        ),
        migrations.AddField(
            model_name='choice2',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mysite.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
    ]
